TCCPP/wheatley

src/components/wiki.ts
Resolves #3.  I'd like to have some eyes on this, since I'm not familiar with the code base, and there do not appear to be any output tests.
=> Fix escaping issue in mock code markup

src/wheatley.ts
This was giving me IDE false positive warnings about unhandled promise rejections, and it was ugly anyway.
=> Refactor wheatley channel fetch

README.md, src/infra/database-interface.ts, src/wheatley.ts
Fixes #19.
Further work is required to make MongoDB truly optional, outside of freestanding mode.
=> Disable mongo for freestanding, refactor

wiki_articles/as_if.md
=> Add as-if rule article

package-lock.json, src/components/autoreact.ts
Might be some funny business on some node files related to how I set stuff up as I've not used node itself much.
Otherwise I only added a condition to Wheatley's Autoreact that checks if a message contains the string `what?` and if so will look for a reaction called `thcampbell` and if it exists applies it.
=> Added reaction to posts containing 'what?'

wiki_articles/stdc++.md
=> Add wiki article about bits/stdc++.h

wiki_articles/cp.md
First version of the competitive programming macro to help explain why helping with CP can be tricky, I hope this command can be helpful in explaining to people why helping with CP questions can be difficult and improving things for both the asker and the helpers(s)
=> Competitive programming wiki article

src/components/anti-everyone.ts
Fix #22.
I would like some help landing on a better wording for the response.
Also, maybe the event should be logged somewhere to improve mod awareness.
=> Respond to users attempting to ping everyone

src/components/wiki.ts, src/wheatley.ts
There is an unconditional fetching of TCCPP channels in freestanding mode.
Also, the fact that channel IDs are no longer hardcoded breaks freestanding wiki article parsing.
=> Fix freestanding issues preventing bot startup

wiki_articles/learn_cpp.md
=> update howto learn C++

package-lock.json, package.json, src/components/anti-executable.ts, src/infra/virustotal.ts, src/wheatley.ts
=> Prevent executable file uploads

src/components/c-help-redirect.ts
https://en.wikipedia.org/wiki/Klempen
=> fix infuriating bot message

.gitmodules
they were moved to the TCCPP organization
=> update submodule urls

wiki_articles/getting_started_with_vs.md
Add getting_started_with_vs article
Wording revisions welcome
See what it looks like in [this Discord message](https://discord.com/channels/331718482485837825/506274405500977153/1220371460250669116)
=> Add getting_started_with_vs article

wiki_articles/compilation_steps.md
Add compilation_steps article
Looks a bit like a wall of text, can't really seem to figure out how to make it look more digest, revisions and advice welcome
See what it looks like in [this Discord message](https://discord.com/channels/331718482485837825/506274405500977153/1220341838280523888)
=> Add compilation_steps article

wiki_articles/template_argument_deduction.md, wiki_articles/template_instantiation.md
Sorry I forgor to push a commit 💀 
This fixes the formatting for template articles and corrects a couple typos
=> Fix template articles

src/components/moderation/moderation-common.ts, src/utils/arrays.ts
Said we should make a funni response if a mod tries to ban themselves. Was told to make a PR. Here I am.  ;)
=> Add in funni response if a mod tries to ban themselves

wiki-articles/ask.md, wiki-articles/bitint.md, wiki-articles/c-cpp-files.md, wiki-articles/cheats.md, wiki-articles/compilation-steps.md, wiki-articles/formatting.md, wiki-articles/ide.md, wiki-articles/int-size.md, wiki-articles/llm.md, wiki-articles/pi.md, wiki-articles/precedence.md, wiki-articles/recursion.md, wiki-articles/safety.md, wiki-articles/std-flags.md
C/C++ is very misleading; they are completely separate languages.
=> Replace C/C++ with C and C++

src/components/redirect.ts
Details: https://discord.com/channels/331718482485837825/802541516655951892/1306268137926295572
=> Disallow command `/r` on help channels

src/wheatley.ts
Added get_channel along with one other function as discussed over discord.
=> Implement get_channel

Makefile, README.md, dev-container/Dockerfile, dev-container/entry.sh
Simple development container system using podman
=> Development container setup

src/components/role-manager.ts
resolves #128 by introducing gimmepink/unpink commands
=> Add gimmepink/unpink commands

tsconfig.json
=> Generate source map

src/modules/tccpp/components/the-button.ts
and fix a tiny issue of the setup command not assigning the message
=> Modernize The Button commands

src/components/moderation/voice-deputies.ts, src/wheatley.ts
This reorganizes all voice moderation commands under a common /voice command and adds commands for voice moderators to assign and take away the voice role.
=> Add voice role

src/modules/tccpp/components/permissions-manager.ts
* Remove walled voice section,
* make voice passive by default, restrict active participation to members with voice or Intermediate+ as well as server boosters,
* allow voice moderators to change voice status,
* cleanup moderator permissions.
=> Change voice permissions
