- src/components/wiki.ts
This was giving me IDE warnings. Also IIRC there are ESLint rules that detect this. Better for code quality to have it fixed.
> Fix redundant square bracket escape in regex

- src/components/anti-screenshot.ts
This basically just pulls out the creation of the embed and removes `create_embed`, which was only used in one place, and didn't have much of a right to exist.
I initially wanted to fix #12, but was unable to locate the source of the problem. Perhaps the screenshot component is duplicated in `wheatley-private`?
> Refactor anti-screenshot

- wiki_articles/pi.md
Firstly, I feel like the `after` is too awkward; no one has phrased it that way in other resources afaik. cppreference always uses `since`, which makes sense for C23 since that standard is now feature-complete. However, it arguably doesn't make sense in C++26. I propose `in` as a neutral term.
Also, the recommendation for C isn't totally correct, because `constexpr` can only be used with GNU extensions there. Also, these variables cannot be global because static initialization is too limited.
We don't want to recommend macros, so the only sane alternative I see is to recommend manual constants.
> Change recommendations for C

- wiki_articles/pi.md
As recommended in #28, this follow-up PR limits the precision to just enough digits for the *binary128* format.
This requires having no space between `=3`, otherwise it wouldn't fit on a single line. Overall, this PR makes the embed one line shorter.
> Limit precision to binary128 format

- src/command.ts
- src/components/bikeshed.ts
> Add /bikeshed command component

- wiki_articles/std_array.md
The warning bullet on decay currently spans two lines, which is bad.
Also this adds another `:no_entry:` bullet which informs about a likely bug. Comparisons between arrays have been deprecated in C++23 and are likely going to be removed in C++26. See https://stackoverflow.com/q/12866413/5740428
> Update article on `std::array`

- wiki_articles/channel.md
Some of the channels listed in this wiki article are now archived, so I updated the links.
> modmail-139: update channel list in wiki page

- src/components/forum-channels.ts
In the !solved reminder message.
I can imagine beginners being confused by being asked to run something, and beginners (both C++ beginners and Discord beginners) are the most likely to receive those messages.
See also: https://discord.com/channels/331718482485837825/1163560216319766669
> replaced "run !solved" with clearer "type !solved"

- src/components/server-suggestion-tracker.ts
Closes #9
Applies to both "Suggestion resolved" and "suggestion reopened" messages, since both should show up in thread previews.
> Send suggestion resolved/reopened as regular messages

- src/components/c-help-redirect.ts
Closes #26 
Automatically checks code blocks posted in #c-help-text, and if it detects C++ code, informs the user.
Also has a manual /not-c command, for cases when the automated check doesn't catch something.
Note: the message will still trigger if someone tries to cheat the system, like calling a variable "template" or something.
> component to check for c++ code in c-help-text channel

- wiki_articles/overload_less.md
Commit https://github.com/TCCPP/wheatley/commit/7f29c9f6c305eac0ece2b0a2684ff8ba2031155b which applied suggested changes in https://github.com/TCCPP/wheatley/issues/63 accidentally broke the grammar in one sentence.
Note that even if the "if" was removed and the new sentence was grammatically correct, it would be semantically incorrect because overloading `<` in itself does not satisfy *LessThanComparable*; a strict weak ordering is required, as the old wording states.
> Fix broken grammar in wiki article

- src/components/redirect.ts
Most of the times, users do not only ask for help in #c-cpp-discussion and #general-discussion, but other off-topic channels as well. It has been observed by many members, so I believe that `!r` should be allowed outside the aforementioned two channels.
> Always redirect users to help channels

- src/components/anti-everyone.ts
This disables the reply message if a link-like string is detected inside of `@everyone`/`@here` messages, mainly to not allow advertisements to stay up within Weatley's reply.
> Disable auto-reply if a link is detected in the output

- wiki_articles/template_argument_deduction.md
- wiki_articles/template_instantiation.md
Add template_argument_deduction and template_instantiation articles
Kinda big, but on the okay side of it IMHO.
See what they look like in [this Discord message](https://discord.com/channels/331718482485837825/506274405500977153/1220326543193014345) and [this one](https://discord.com/channels/331718482485837825/506274405500977153/1220334961530503258).
Since Wheatley doesn't seem to be rendering inline tags correctly, I went ahead and did this little bit of a montage to give a better idea of how they will (hopefully) end up looking:
> Add template_argument_deduction and template_instantiation articles

- src/components/the-button.ts
Currently there is no manner with The Button to be able to tell what your current score is without pressing the button. This minor addition adds your current score to the scoreboard button when pressed.
I've kept this change pretty minor, but another possibility is to also display your current ranking. I've though for the time being kept the change small.
> Add users current score to the scoreboard

- src/utils/__tests__/containers.ts
- src/utils/containers.ts
- test/containers.ts
- vitest.config.ts
I made this little code change to have a global data cleanup timer for *all* `SelfClearingSet` and `SelfClearingMap`, which allows easier cleanup without having to call `.destroy`.
TODO:
> Optimize self cleaning containers

- wiki-articles/template-argument-deduction.md
The following fixes/improvements are made:
1. "Function template" is the right term; see https://eel.is/c++draft/temp.fct
2. The standard term to describe "providing" template arguments is "explicitly specifying"; see https://eel.is/c++draft/temp.arg.explicit. The article once calls this "not provided" and once calls it "imposing". Instead of inventing new words for this (and being inconsistent within the same article), let's just use the standard terminology.
3. "Match `T` to" can be replaced with "deduce `T` from". Since the article is already talking about template argument deduction, it only makes sense to use the standard terminology. On top of that, the article later says "deduce template parameters", so it does use standard terminology, just not consistently.
4. It is not true that …
> Improve wording of template-argument-deduction article

- wiki-articles/template-instantiation.md
A few things in the article aren't quite right and should be corrected:
1. A template is an [entity](https://eel.is/c++draft/basic.pre#def:entity) by definition. However, it would be correct to say that a function template is not a function.
2. To my knowledge, "deriving to" or "deriving into" isn't correct English. However, you can say "turning into", which most would consider simpler language anyway.
3. It's called "function template", but the heading says "template function". We don't need to be pedantically correct in these articles, but at least we should use the terminology from the standard/cppreference.
> Fix various wording problems with template-instantiation article

- README.md
- src/bot-component.ts
- src/wheatley.ts
In passive mode, Wheatley will not advertise or react to commands, and only load components that are marked as passive. This is to allow additional secondary instances of the bot to coexist with a running primary instance on the same server without interference, e.g., for testing new features.
> Introduce passive mode

- src/components/anti-invite-links.ts
Users should be able to send invites to tccpp when in tccpp otherwise are we really in the tccpp discord???
> feat: whitelist our own invite

- src/common.ts
- src/components/moderation/moderation-common.ts
- src/components/moderation/timeout.ts
- src/utils/strings.ts
Closes #114.
I've had some issues running checks, so this is probably going to fail some lint checks, but here's the idea for now.
> Improve duration parsing and error feedback

- src/components/permissions-manager.ts
Closes #112.
`PermissionManager` relies on TCCPP. In freestanding, you get a `TypeError` when it accesses `this.wheatley.roles.muted.id`.
> Make `PermissionManager` not freestanding

- dev-container/Dockerfile
- dev-container/entry.sh
We discussed this a few weeks back and I had found the solution back then, but actually never got around to sending in a PR for the issue.
Here is the patch that allows podman to actually work using windows wsl. I've not yet tested this code on linux so will need ci to double check there is no regression on the linux end.
> Fix issue with podman not working on windows wsl

- Makefile
- src/components/starboard.ts
I created a feature so that not all of the reaction spots cannot be filled up unless one of them is a negative reaction. This is to prevent users from filling up all spots from a delet_this or another negative reaction.
Created one new function `should_delete_reaction()` to check if it should be deleted
I also fixed a typo in the Makefile.
> Implemented feature to not fill up all reaction spots in #memes

- README.md
- src/bot-component.ts
- src/command-manager.ts
- src/wheatley.ts
Slash commands can be limited to specific users/roles/channels in server settings, making passive mode a very crude attempt at doing what can already be done in a much simpler and more precise way. Thus, passive mode is probably best removed again.
> Revert passive mode

- tsconfig.json
simplify and future-proof build by including only `src/` instead of excluding everything else.
> Simplify build

- tsconfig.json
This reverts commit 57140d7cbe406492d7b0436be012c53b21ce4e14, which broke the `lint-files` step.
> Revert "Simplify build (#138)"

- README.md
- config.default.json
- src/components/anti-executable.ts
- src/components/moderation/modlogs.ts
- src/wheatley.ts
* Removes the global `TCCPP_ID`, `WHEATLEY_ID`, and `zelis` variables.
* Introduces a `mom` config option to specify the user to run to when something goes wrong.
* Replaces `wheatley.parameters` with a general `wheatley.config` that contains only keys not used by the bot core.
> Clean up a couple things

- README.md
We should have an example to illustrate how to exclude specific components (it's important to use the .js extension).
> Add back example

- README.md
it keeps messing up the comment formatting…
> Don't autoformat example json

- src/components/moderation/moderation-common.ts
- src/components/moderation/moderation-control.ts
- src/components/moderation/modlogs.ts
- src/components/moderation/modmail.ts
- src/components/moderation/modstats.ts
- src/components/moderation/purge.ts
- src/components/nodistractions.ts
- src/components/notify-about-formerly-banned-users.ts
- src/components/pin-archive.ts
- src/components/role-manager.ts
- src/modules/tccpp/components/april1/buzzwords.ts
- src/modules/tccpp/components/days-since-last-incident.ts
- src/modules/tccpp/components/roulette.ts
- src/modules/tccpp/components/server-suggestion-tracker.ts
- src/modules/tccpp/components/skill-role-suggestion.ts
- src/modules/tccpp/components/starboard.ts
- src/modules/tccpp/components/the-button.ts
- src/wheatley.ts
* cleans up client code by moving all the `unwrap()` calls into the getter
* also adds a couple `private` and `readonly` modifiers
> Make database readonly

- src/components/moderation/rolepersist.ts
- src/modules/tccpp/components/permissions-manager.ts
- src/wheatley.ts
and move permissions-manager.ts into tccpp module
> Update voice permissions

- src/components/moderation/massban.ts
- src/components/moderation/moderation-common.ts
- src/components/moderation/moderation-control.ts
- src/components/moderation/modlogs.ts
- src/components/moderation/note.ts
- src/components/wiki.ts
- src/wheatley.ts
- test/wiki-articles.ts
Fetch emoji from guild and application dynamically instead of hardcoding TCCPP emoji ids.
* Wheatley status emoji now use standard Unicode symbols as a fallback, replaced with application emoji of the same name on startup (if one exists).
* Wiki component now simply makes all guild emoji and channels (at least those with sufficiently sane names) available for use in articles.
> Refactor emoji stuff

- src/components/dynamic-room-size.ts
Allow voice moderators to change the user limit of the channel they're currently in. Pushing a new limit replaces the previous limit. The limit is automatically reset to the original value the moment all moderators have left the chat.
> Add dynamic room size
